### ISSUE TITLE
running npm start --env=dev

### ISSUE THREAD

**Issue by logicappsource** [anujsharma-bbd/react-environments#1]
> node node_modules/react-environments --path=src/environments
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '/User/node_modules/react-environments'

package.json: 
 "prestart": "node node_modules/react-environments --path=src/environments",
 "prebuild": "node node_modules/react-environments --path=src/environments",

module.exports = {
   "REACT_APP_NODE_ENV": "production",
   "REACT_APP_API_URL": "https://api.mynordicroom.com/api",
   "REACT_APP_SOCKET_URL": "https://api.mynordicroom.com"
}

module.exports = {
   "REACT_APP_NODE_ENV" : "development",
   "REACT_APP_API_URL" : "http://localhost:6582/api",
   "REACT_APP_SOCKET_URL" : "http://localhost:3000"
}

**Comment by logicappsource** [comment]
./src/environments/environment.js
  Line 1:1:  'module' is not defined  no-undef


Please help

**Comment by anujsharma-bbd** [comment]
@logicappsource sorry for late reply, have you used "npm i react-environments" ?

**Comment by anujsharma-bbd** [comment]
@logicappsource : can you show the environemnt.js content here ? it should have module export like rest of the env files
